name: AWS Lambda invoke 테스트

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: AWS Lambda invoke test
    runs-on: ubuntu-latest

    steps:
      - name: AWS 변수 설정
        run: |
          echo "AWS_OIDC_ROLE_ARN=${{ secrets.AWS_OIDC_ROLE_ARN }}" >> $GITHUB_ENV
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339713142100:oidc-provider/token.actions.githubusercontent.com
          aws-region: ap-northeast-2

      - name: Invoke Lambda function
        run: |
          aws lambda invoke \
            --function-name curl \
            output.txt
          cat output.txt
